import Head from 'next/head'

export default function Home() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100">
      <Head>
        <title>Simple MVP Test</title>
        <meta name="description" content="Test project for simplified MVP architecture" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto px-4 py-16">
        <div className="text-center">
          <h1 className="text-5xl font-bold text-gray-900 mb-6">
            Simple MVP Test
          </h1>
          <p className="text-xl text-gray-600 mb-8">
            Test project for simplified MVP architecture
          </p>
          
          <div className="max-w-md mx-auto p-6 bg-white rounded-lg shadow-lg">
            <div className="text-lg text-gray-700">
              ✅ Generated by VibeBuilder AI
            </div>
            <div className="text-sm text-gray-500 mt-2">
              Deployed automatically to Vercel
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}